sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vickykrish/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vickykrish/docker-react npm run test

